name: monglee
description: 몽글이 -> todoList앱
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^2.0.1
  freezed_annotation: ^2.4.1
  flutter_local_notifications: ^15.1.1
  hive: ^2.2.3
  image_picker: ^1.0.4
  permission_handler: ^10.4.3
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  freezed: ^2.3.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7

flutter:
  uses-material-design: true
