name: monglee
description: 몽글이 -> todoList앱
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.6 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get: ^4.6.5
  logger: ^2.0.1
  flutter_local_notifications: ^15.1.1
  image_picker: ^1.0.4
  permission_handler: ^10.4.3
  firebase_crashlytics: ^3.3.5
  firebase_core: ^2.15.1
  firebase_remote_config: ^4.2.5
  firebase_dynamic_links: ^5.3.5
  flutter_svg: ^2.0.7
  table_calendar: ^3.0.9
  svg_to_font: ^1.0.2
  easy_localization: ^3.0.3
  extended_image: ^8.1.1
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  freezed_annotation: ^2.4.1
  sqflite: ^2.3.0
  path: ^1.8.3
  package_info_plus: ^4.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  json_serializable: ^6.1.4
  build_runner: ^2.1.7
  day_night_time_picker: ^1.3.0+1
  freezed: ^2.4.5

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/fonts/
    - assets/translations/
  fonts:
    - family: pretendard
      fonts:
        - asset: assets/fonts/pretendard_thin.otf
          weight: 100
        - asset: assets/fonts/pretendard_extra_light.otf
          weight: 200
        - asset: assets/fonts/pretendard_light.otf
          weight: 300
        - asset: assets/fonts/pretendard_regular.otf
          weight: 400
        - asset: assets/fonts/pretendard_medium.otf
          weight: 500
        - asset: assets/fonts/pretendard_semi_bold.otf
          weight: 600
        - asset: assets/fonts/pretendard_bold.otf
          weight: 700
        - asset: assets/fonts/pretendard_extra_bold.otf
          weight: 800
        - asset: assets/fonts/pretendard_black.otf
          weight: 900
    - family: uhbeem
      fonts:
        - asset: assets/fonts/uhbeem.ttf
        - asset: assets/fonts/uhbeem_bold.ttf